glance_db_user: "glance"
glance_keystone_user: "glance"
glance_keystone_password: "YourSecurePasswordHERE"
glance_db_password: "YourSecurePasswordHERE"
glance_db_address: "172.16.1.2"
memcached_ip: 172.16.1.2
rabbitmq_address: "172.16.1.2"
rabbitmq_username: admin
rabbitmq_password: admin
openstack_project: "services"
openstack_domain: "default"
keystone_address: "172.16.1.2"
glance_rbd_user: glance
glance_rbd_secret_uuid: 9f8e7d6c-5b4a-3f2e-1d0c-9b8a7f6e5d4c