- name: neutron_restart
  service: 
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
