---
release_kubernetes = "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
gpg_apt = "https://pkgs.k8s.io/core:/stable:/v1.30/deb/"
CRICTL_VERSION="v1.30.1"
CRICTL_ARCH="$(dpkg --print-architecture)"

