- name: ----- install pre-requisite  controll plane -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-openvswitch-agent 
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - openvswitch-switch
    - neutron-l3-agent 
    - neutron-metadata-agent
    - python3-neutronclient
    - neutron-linuxbridge-agent
  tags: [ neutron ]
  when: 
    - neutron_controll == "enabled"



- name: ----- install pre-requisite  compute plane -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - openvswitch-switch
    - neutron-openvswitch-agent
  tags: [ neutron ]
  when: 
    - neutron_compute == "enabled"


- name: copy configuration neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  when: 
    - neutron_controll == "enabled"
  tags: [ neutron , copy ]

- name: copy configuration ml2_conf
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  when: 
    - neutron_controll == "enabled"
  tags: [ neutron ]

- name: copy configuration openvswitch_agent.ini
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/openvswitch_agent.ini
  when: 
    - neutron_controll == "enabled"
  tags: [ neutron ]


- name: run sync db for neutron
  shell: |
    /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  when: 
    - neutron_controll == "enabled"
  notify: neutron_restart
  tags: [ neutron ]


