- name: Gather installed package facts
  package_facts:
    manager: auto
  when: ceph == "enabled" 
  tags: [ ceph ]

- name: install rsync 
  apt:
    name: rsync
    state: present
    update_cache: yes
  tags: [ ceph ]

- name: Check if Docker is installed
  set_fact:
    docker_installed: "{{ 'docker-ce' in ansible_facts.packages }}"
  when: ceph == "enabled"
  tags: [ ceph ]


- name: Install prerequisites
  apt:
    name:
      - software-properties-common
      - python3-pip

    state: present
    update_cache: yes
  tags: [ ceph ]
  when: ceph == "enabled"



- name: Add Ceph repository key
  get_url:
    url: https://download.ceph.com/keys/release.asc
    dest: /etc/apt/keyrings/ceph.asc
    mode: '0644'
  tags: [  ceph ]
  when: ceph == "enabled"

- name: Add Ceph Reef repository (use jammy for noble)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/ceph.asc] https://download.ceph.com/debian-reef/ jammy main"
    state: present
    filename: ceph
  when: ceph == "enabled"
  tags: [  ceph ]

- name: Install cephadm (modern deployment tool)
  apt:
    name: cephadm
    state: present
  tags: [  ceph ]
  when: monitor == "enabled"


- name: install docker services on all nodes
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
  - ca-certificates
  - curl
  tags: [ ceph_inst ]
  when: 
  - not docker_installed

  tags: [  ceph ]


- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: [  ceph ]
  when: 
  - ceph == "enabled"
  - not docker_installed

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  tags: [  ceph ]
  when: 
  - ceph == "enabled"
  - not docker_installed


- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags: [  ceph ]
  when: 
  - ceph == "enabled"
  - not docker_installed


# - name: Update apt cache
#   apt:
#     update_cache: yes
#   tags: [ ceph ]
#   when: 
#   - ceph == "enabled"
#   - not docker_installed


- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

  when: 
  - ceph == "enabled"
  - not docker_installed
  tags: [  ceph ]




# Ceph Monitors Setup
- name: Create Ceph cluster directory
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'
  tags: [  ceph ]
  when: monitor == "enabled"

- name: Bootstrap Ceph cluster
  shell: >
    cephadm bootstrap
    --mon-ip {{ initial_ceph_mon }}
    --cluster-network {{ ceph_cluster_network }}
    --skip-monitoring-stack 
    --initial-dashboard-user {{ dashboard_username }}
    --initial-dashboard-password {{ dashboard_password }}
    --dashboard-password-noupdate
    --skip-pull

  args:
    creates: /etc/ceph/ceph.conf
  tags: [  ceph ]
  when: hostname == "ubuntu-01"



- name: Check Ceph cluster status
  shell: ceph status
  register: ceph_status
  ignore_errors: yes
  when: hostname == "ubuntu-01"
  tags: [  ceph ]

- name: Display Ceph cluster status
  debug:
    var: ceph_status.stdout
  when: hostname == "ubuntu-01"
  tags: [  ceph ]



- name: Generate /etc/hosts for all nodes
  lineinfile:
    path: /etc/hosts
    # Match the IP at the start of the line
    regexp: "^{{ hostvars[item]['host_ip'] }}.*"
    # Format: IP Hostname
    line: "{{ hostvars[item]['host_ip'] }} {{ hostvars[item]['hostname'] }}"
    state: present
  # Loop through every host in your [openstack] group
  loop: "{{ groups['openstack'] }}"
  # This runs on the target, but pulls data from the whole inventory
  delegate_to: "{{ inventory_hostname }}"
  tags: [  ceph ]


- name: generate ceph pub on mon nodes
  shell: 'ssh-copy-id -o "StrictHostKeyChecking=no" -f -i /etc/ceph/ceph.pub root@{{ item }}'
  loop: "{{ ceph_mon_nodes[1:] }}"  # skip bootstrap
  tags: [  ceph ]
  when: hostname == "ubuntu-01"


- name: generate ceph pub on osd nodes
  shell: 'ssh-copy-id -o "StrictHostKeyChecking=no" -f -i /etc/ceph/ceph.pub root@{{ item }}'
  loop: "{{ ceph_osd_nodes }}"  # skip bootstrap
  tags: [  ceph ]
  when: hostname == "ubuntu-01"



- name: Add additional  nodes
  shell: "ceph orch host add {{ item }}"
  loop: "{{ ceph_mon_nodes[1:] }}"  # skip bootstrap
  tags: [ceph]
  when: hostname == "ubuntu-01"


- name: Add additional  nodes
  shell: "ceph orch host add {{ item }}"
  loop: "{{ ceph_osd_nodes[1:] }}"  # skip bootstrap
  tags: [ceph]
  when: hostname == "ubuntu-01"


- name: Apply monitor placement policy
  shell: "ceph orch apply mon --placement='{{ ceph_mon_nodes | join(',') }}'"
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph]
  



- name: Wipe disks for OSD use
  shell: "wipefs -a {{ item }}"
  with_items: "{{ osd_device.split(',') }}"
  when: 
    - osd == "enabled"
    - osd_device is defined
  tags: [  ceph]

- name: Create OSDs
  shell: "ceph-volume lvm create --data {{ item }}"
  register: osd_create
  failed_when: false
  with_items: "{{ osd_device.split(',') }}"
  when: 
    - osd == "enabled"
    - osd_device is defined
  tags: [  ceph]


- name: create pool for cinder 
  shell: "{{ item }}"
  with_items:
  - ceph osd pool create cinder-volumes 64 64 replicated
  - ceph osd pool set cinder-volumes size 3
  - ceph osd pool set cinder-volumes min_size 2
  - ceph osd pool application enable cinder-volumes rbd
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph]
  
#IF OSD =>6
# - name: create pool for glance 
#   shell: "{{ item }}"
#   with_items:
#   - ceph osd erasure-code-profile set glance-ec-profile  k=4 m=2 crush-failure-domain=host technique=reed_sol_van
#   - ceph osd pool create glance-images 64 64 erasure glance-ec-profile
#   - ceph osd pool set glance-images allow_ec_overwrites true
#   - ceph osd pool application enable glance-images rbd
  # when: hostname == "ubuntu-01"
  # run_once: true
  # tags: [  ceph]
  

#IF OSD < 6
- name: create pool for glance 
  shell: "{{ item }}"
  with_items:
  - ceph osd pool create glance-images 64 64 replicated
  - ceph osd pool set glance-images size 2
  - ceph osd pool set glance-images min_size 1
  - ceph osd pool application enable glance-images rbd
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph ]
  



- name: Create Ceph user for Cinder
  command: >
    ceph auth get-or-create client.cinder
    mon 'profile rbd'
    osd 'profile rbd pool=volumes, profile rbd pool=cinder-volumes, profile rbd-read-only pool=cinder-volumes'
    mgr 'profile rbd pool=volumes, profile rbd pool=cinder-volumes'
  register: cinder_key
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph ]

- name: Create Ceph user for Glance
  command: >
    ceph auth get-or-create client.glance
    mon 'profile rbd'
    osd 'profile rbd pool=glance-images'
    mgr 'profile rbd pool=glance-images'
  register: glance_key
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph ]

- name: Create Ceph user for Nova
  command: >
    ceph auth get-or-create client.nova
    mon 'profile rbd'
    osd 'profile rbd pool=cinder-volumes, profile rbd-read-only pool=cinder-volumes'
    mgr 'profile rbd pool=cinder-volumes'
  register: nova_key
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph ]


- name: Export Ceph keyrings
  shell: "ceph auth get client.{{ item }} -o /etc/ceph/ceph.client.{{ item }}.keyring"
  loop:
    - cinder
    - glance
    - nova
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph_key ]

- name: Fetch ceph.conf to controller
  fetch:
    src: /etc/ceph/ceph.conf
    dest: /tmp/ceph.conf
    flat: yes
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph ]

- name: Fetch keyrings to controller
  fetch:
    src: "/etc/ceph/ceph.client.{{ item }}.keyring"
    dest: "/tmp/ceph.client.{{ item }}.keyring"
    flat: yes
  loop:
    - cinder
    - glance
    - nova
  when: hostname == "ubuntu-01"
  run_once: true
  tags: [  ceph_key ]


- name: Install Ceph client packages
  apt:
    name:
      - ceph-common
      - python3-rbd
    state: present
  tags: [  ceph ]

- name: Create /etc/ceph directory
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'
  tags: [  ceph ]
  when: ceph == "enabled"

- name: Copy Ceph configuration
  synchronize:
    src: /tmp/ceph.conf
    dest: /etc/ceph/ceph.conf
  delegate_to: "{{ groups['openstack'][0] }}"
  tags: [  ceph ]


- name: Copy computes service configuration
  synchronize:
    src: "/tmp/ceph.client.{{ item }}.keyring"
    dest: "/etc/ceph/ceph.client.{{ item }}.keyring"
  loop:
    - cinder
    - glance
    - nova
  delegate_to: "{{ groups['openstack'][0] }}"
  tags: [  ceph_key ]

- name: Deploy nova secret 
  template:
    src: secret.xml.j2
    dest: /tmp/secret.xml
    owner: nova
    group: nova
    mode: '0640'
  notify: nova_compute_restart
  tags: [  ceph_key ]
  when: 
    - nova_compute == "enabled"

- name: Deploy nova secret 
  template:
    src: secret.xml.j2
    dest: /tmp/secret.xml
    owner: nova
    group: nova
    mode: '0640'
  notify: nova_compute_restart
  tags: [  ceph_key ]
  when: 
    - nova_control == "enabled"



- name: Set Libvirt Secret Value
  shell: |
    virsh secret-define --file /tmp/secret.xml
    virsh secret-set-value --secret {{ rbd_secret_uuid }} --base64 $(cat /etc/ceph/client.nova.key)
  when: nova_compute == "enabled"


- name: Set Libvirt Secret Value
  shell: |
    virsh secret-define --file /tmp/secret.xml
    virsh secret-set-value --secret {{ rbd_secret_uuid }} --base64 $(cat /etc/ceph/client.nova.key)
  when: nova_controll == "enabled"

