ceph_mon_nodes: ["ubuntu-01", "ubuntu-02", "ubuntu-03"]
ceph_osd_nodes: ["ubuntu-04", "ubuntu-05"]
initial_ceph_mon: "172.17.1.2"
ceph_cluster_network: "172.17.1.0/24"
dashboard_username:  "admin"
dashboard_password: "admin"
ceph_osd_disks: 
  - { "ubuntu-04":"/dev/vdb" , "ubuntu-05":"/dev/vdb"}
cinder_rbd_secret_uuid: 4b5c6d7e-8a9b-0c1d-2e3f-4a5b6c7d8e9f
glance_rbd_secret_uuid: 9f8e7d6c-5b4a-3f2e-1d0c-9b8a7f6e5d4c