ceph_mon_nodes: ["ubuntu-01", "ubuntu-02", "ubuntu-03"]
ceph_osd_nodes: ["ubuntu-04", "ubuntu-05"]
initial_ceph_mon: "172.17.1.2"
ceph_cluster_network: "172.17.1.0/24"
dashboard_username:  "admin"
dashboard_password: "admin"
ceph_osd_disks: 
  - { "ubuntu-04":"/dev/vdb" , "ubuntu-05":"/dev/vdb"}