 - name: ------remove all sources.list.d 8 ---------------------
   shell: rm -rf /etc/yum.repos.d/* 
   tags: [ install ]

 - name: ---- Install Zabbix-Agent CentOS 8 RPM File ----
   yum:
     name: "{{ centos8_link }}"
     validate_certs: false
   tags: [ install ]
   
 - name: ---- Install Zabbix-Agent On CentOS 8 ----
   yum:
     name: zabbix-agent
     enablerepo: zabbix
     update_cache: true
     state: latest
   tags: [ install ]
