- name: ----- install pre-requisite -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nova-compute
    - python3-rbd
  tags: [ nova_compute , nova]
  when: 
    - nova_compute == "enabled"


- name: ----- install pre-requisite -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nova-api
    - nova-conductor
    - nova-scheduler
  tags: [ nova_controll_install  , nova]
  when: 
    - nova_controll == "enabled"


- name: Deploy nova controll configuration
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: '0640'
  notify: "{{ item }}"
  with_items:
  - nova_control_restart
  tags: [ nova_controll , nova]
  when: 
     - nova_controll == "enabled"



- name: Deploy nova compute configuration
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: '0640'
  notify: "{{ item }}"
  with_items:
  - nova_compute_restart
  tags: [ nova_compute  , nova]
  when: 
    - nova_compute == "enabled"

- name: sync nova-api db 
  shell: "{{ item }}"
  tags: [ nova_controll,nova_compute , nova]
  when: 
    - nova_controll == "enabled"
  with_items:
  - nova-manage api_db sync
  - nova-manage cell_v2 map_cell0
  - nova-manage cell_v2 create_cell --name=cell1 --verbose
  - nova-manage db sync
  tags: [ nova_controll,nova_compute , nova]
  when: 
    - nova_controll == "enabled"


- name: sync nova-api db 
  shell: "{{ item }}"
  tags: [ nova_compute , nova]
  delegate_to: "{{ groups['nova_controll'][0] }}"
  with_items:
  - nova-manage cell_v2 discover_hosts --verbose
  tags: [ nova_controll,nova_compute , nova]


